# Generated by Django 3.2.1 on 2021-05-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='important_reminder',
            new_name='text',
        ),
    ]
