# Generated by Django 3.2.1 on 2021-05-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Registration',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='TorO',
            new_name='Tenantorwner',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='uno',
            new_name='unit',
        ),
    ]
