# Generated by Django 3.2.1 on 2021-05-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210518_0029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
