# Generated by Django 4.0.3 on 2022-04-09 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=10, verbose_name='Mobile No')),
                ('tenantorowner', models.CharField(blank=True, max_length=10, verbose_name='Tenant/owner')),
                ('block', models.CharField(blank=True, max_length=1, verbose_name='Block No.')),
                ('flat', models.CharField(blank=True, max_length=3, verbose_name='Flat No.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
